[font]
normal = { family = "Source Code Pro", style = "Medium" }
bold =   { style = "Bold" }
italic = { style = "Medium Italic" }
bold_italic = { style = "Bold Italic" }
size = 12

[general]
import = [
    "~/.config/alacritty/alacritty-theme/themes/campbell.toml"
]
